INSERT INTO STUDENT (NAME,AGE,DOB,GENDER,CGPA) VALUES ('vignesh',25,PARSEDATETIME('22-06-1994','dd-MM-yyyy'),'m','6.6');
INSERT INTO STUDENT (NAME,AGE,DOB,GENDER,CGPA) VALUES ('divya',24,PARSEDATETIME('17-11-1995','dd-MM-yyyy'),'f','7.0');
INSERT INTO STUDENT (NAME,AGE,DOB,GENDER,CGPA) VALUES ('gayathri',18,PARSEDATETIME('21-11-2001','dd-MM-yyyy'),'f','7.5');
--INSERT INTO STUDENT (NAME,AGE,DOB,GENDER,CGPA) VALUES ('varun',16,PARSEDATETIME('23-02-2003','dd-MM-yyyy'),'m','7.7');


INSERT INTO TEACHER (NAME,AGE,DOB,GENDER,"EXP") VALUES ('babu',52,PARSEDATETIME('17-03-1967','dd-MM-yyyy'),'m',20);